package dk.cintix.application.server.rest.http;

import dk.cintix.application.server.TestSupport;
import dk.cintix.application.server.infrastructure.annotations.Action;
import dk.cintix.application.server.infrastructure.annotations.ApiDoc;
import dk.cintix.application.server.infrastructure.annotations.ApiTag;
import dk.cintix.application.server.infrastructure.annotations.DELETE;
import dk.cintix.application.server.infrastructure.annotations.GET;
import dk.cintix.application.server.infrastructure.annotations.POST;
import dk.cintix.application.server.infrastructure.annotations.PUT;
import dk.cintix.application.server.modules.http.server.endpoint.RestHttpServer;
import dk.cintix.application.server.modules.http.server.services.domain.models.Response;
import dk.cintix.application.server.modules.openapi.OpenApiService;
import java.util.List;
import java.util.Map;

public class OpenApiServiceTest {

    private RestHttpServer server;

    public void runAll() {
        generatesSpecWithTitleAndVersion();
        generatesPathsFromRegisteredEndpoints();
        apiDocSummaryOverridesAutoGenerated();
        apiDocTagOverridesAutoTag();
        apiTagOnClassSetsDefaultTag();
        detectsPathParameters();
        skipsRegexPatternKeys();
        multipleMethodsOnSamePathAreMerged();
        httpMethodsAreCorrect();
        deprecatedFlagIsSet();
    }

    // --- Happy paths ---

    public void generatesSpecWithTitleAndVersion() {
        // Arrange
        OpenApiService service = new OpenApiService("Test API", "2.0.0", new java.util.LinkedHashMap<>());

        // Act
        Map<String, Object> spec = service.generate();

        // Assert
        TestSupport.assertEquals("3.0.3", spec.get("openapi"), "wrong openapi version");

        @SuppressWarnings("unchecked")
        Map<String, Object> info = (Map<String, Object>) spec.get("info");
        TestSupport.assertEquals("Test API", info.get("title"), "wrong title");
        TestSupport.assertEquals("2.0.0", info.get("version"), "wrong version");
    }

    public void generatesPathsFromRegisteredEndpoints() {
        // Arrange
        server = new RestHttpServer() {};
        server.addEndpoint("/api", new TestEndpoint());
        OpenApiService service = new OpenApiService("API", "1.0", server.getRegisteredEndpoints());

        // Act
        Map<String, Object> spec = service.generate();

        // Assert
        @SuppressWarnings("unchecked")
        Map<String, Object> paths = (Map<String, Object>) spec.get("paths");
        TestSupport.assertTrue(paths.containsKey("/api/items"), "missing /api/items path");
        TestSupport.assertTrue(paths.containsKey("/api/items/{id}"), "missing /api/items/{id} path");
    }

    public void apiDocSummaryOverridesAutoGenerated() {
        // Arrange
        server = new RestHttpServer() {};
        server.addEndpoint("/api", new TestEndpoint());
        OpenApiService service = new OpenApiService("API", "1.0", server.getRegisteredEndpoints());

        // Act
        Map<String, Object> spec = service.generate();

        // Assert
        @SuppressWarnings("unchecked")
        Map<String, Object> paths = (Map<String, Object>) spec.get("paths");
        @SuppressWarnings("unchecked")
        Map<String, Object> itemsPath = (Map<String, Object>) paths.get("/api/items");
        @SuppressWarnings("unchecked")
        Map<String, Object> getOp = (Map<String, Object>) itemsPath.get("get");
        TestSupport.assertEquals("list all items", getOp.get("summary"), "summary should use @ApiDoc value");
    }

    public void apiDocTagOverridesAutoTag() {
        // Arrange
        server = new RestHttpServer() {};
        server.addEndpoint("/api", new TestEndpoint());
        OpenApiService service = new OpenApiService("API", "1.0", server.getRegisteredEndpoints());

        // Act
        Map<String, Object> spec = service.generate();

        // Assert
        @SuppressWarnings("unchecked")
        Map<String, Object> paths = (Map<String, Object>) spec.get("paths");
        @SuppressWarnings("unchecked")
        Map<String, Object> itemsPath = (Map<String, Object>) paths.get("/api/items");
        @SuppressWarnings("unchecked")
        Map<String, Object> getOp = (Map<String, Object>) itemsPath.get("get");

        @SuppressWarnings("unchecked")
        List<String> tags = (List<String>) getOp.get("tags");
        TestSupport.assertEquals("CustomTag", tags.get(0), "tag should use @ApiDoc tag value");
    }

    public void apiTagOnClassSetsDefaultTag() {
        // Arrange
        server = new RestHttpServer() {};
        server.addEndpoint("/api", new TaggedEndpoint());
        OpenApiService service = new OpenApiService("API", "1.0", server.getRegisteredEndpoints());

        // Act
        Map<String, Object> spec = service.generate();

        // Assert
        @SuppressWarnings("unchecked")
        Map<String, Object> paths = (Map<String, Object>) spec.get("paths");
        @SuppressWarnings("unchecked")
        Map<String, Object> dataPath = (Map<String, Object>) paths.get("/api/data");
        @SuppressWarnings("unchecked")
        Map<String, Object> getOp = (Map<String, Object>) dataPath.get("get");

        @SuppressWarnings("unchecked")
        List<String> tags = (List<String>) getOp.get("tags");
        TestSupport.assertEquals("DataLayer", tags.get(0), "tag should use @ApiTag name");
    }

    public void detectsPathParameters() {
        // Arrange
        server = new RestHttpServer() {};
        server.addEndpoint("/api", new TestEndpoint());
        OpenApiService service = new OpenApiService("API", "1.0", server.getRegisteredEndpoints());

        // Act
        Map<String, Object> spec = service.generate();

        // Assert
        @SuppressWarnings("unchecked")
        Map<String, Object> paths = (Map<String, Object>) spec.get("paths");
        @SuppressWarnings("unchecked")
        Map<String, Object> itemPath = (Map<String, Object>) paths.get("/api/items/{id}");
        @SuppressWarnings("unchecked")
        Map<String, Object> getOp = (Map<String, Object>) itemPath.get("get");

        @SuppressWarnings("unchecked")
        List<Map<String, Object>> params = (List<Map<String, Object>>) getOp.get("parameters");
        TestSupport.assertTrue(params != null, "should have parameters");
        TestSupport.assertEquals(1, params.size(), "should have 1 path param");
        TestSupport.assertEquals("id", params.get(0).get("name"), "param name should be id");
        TestSupport.assertEquals("path", params.get(0).get("in"), "param should be in path");
        TestSupport.assertEquals(true, params.get(0).get("required"), "path param should be required");
    }

    public void skipsRegexPatternKeys() {
        // Arrange
        server = new RestHttpServer() {};
        server.addEndpoint("/api", new RegexVerifyEndpoint());
        OpenApiService service = new OpenApiService("API", "1.0", server.getRegisteredEndpoints());

        // Act
        Map<String, Object> spec = service.generate();

        // Assert
        @SuppressWarnings("unchecked")
        Map<String, Object> paths = (Map<String, Object>) spec.get("paths");
        // Should not contain regex keys (keys starting with ^)
        for (String key : paths.keySet()) {
            TestSupport.assertFalse(key.startsWith("^"), "should not contain regex keys: " + key);
        }
        // Should contain the literal paths
        TestSupport.assertTrue(paths.containsKey("/api/regex-test"), "should have /api/regex-test");
        TestSupport.assertTrue(paths.containsKey("/api/regex-test/{id}"), "should have /api/regex-test/{id}");
    }

    // --- Edge cases ---

    public void multipleMethodsOnSamePathAreMerged() {
        // Arrange
        server = new RestHttpServer() {};
        server.addEndpoint("/api", new CrudEndpoint());
        OpenApiService service = new OpenApiService("API", "1.0", server.getRegisteredEndpoints());

        // Act
        Map<String, Object> spec = service.generate();

        // Assert
        @SuppressWarnings("unchecked")
        Map<String, Object> paths = (Map<String, Object>) spec.get("paths");
        @SuppressWarnings("unchecked")
        Map<String, Object> crudPath = (Map<String, Object>) paths.get("/api/crud");
        TestSupport.assertTrue(crudPath.containsKey("get"), "should have GET");
        TestSupport.assertTrue(crudPath.containsKey("post"), "should have POST");
        TestSupport.assertTrue(crudPath.containsKey("put"), "should have PUT");
        TestSupport.assertTrue(crudPath.containsKey("delete"), "should have DELETE");
    }

    public void httpMethodsAreCorrect() {
        // Arrange
        server = new RestHttpServer() {};
        server.addEndpoint("/api", new TestEndpoint());
        OpenApiService service = new OpenApiService("API", "1.0", server.getRegisteredEndpoints());

        // Act
        Map<String, Object> spec = service.generate();

        // Assert
        @SuppressWarnings("unchecked")
        Map<String, Object> paths = (Map<String, Object>) spec.get("paths");

        // POST /api/items
        @SuppressWarnings("unchecked")
        Map<String, Object> itemsPath = (Map<String, Object>) paths.get("/api/items");
        TestSupport.assertTrue(itemsPath.containsKey("post"), "should have POST on /api/items");
        TestSupport.assertTrue(itemsPath.containsKey("get"), "should have GET on /api/items");

        // GET /api/items/{id}
        @SuppressWarnings("unchecked")
        Map<String, Object> itemPath = (Map<String, Object>) paths.get("/api/items/{id}");
        TestSupport.assertTrue(itemPath.containsKey("get"), "should have GET on /api/items/{id}");
        TestSupport.assertTrue(itemPath.containsKey("put"), "should have PUT on /api/items/{id}");
    }

    public void deprecatedFlagIsSet() {
        // Arrange
        server = new RestHttpServer() {};
        server.addEndpoint("/api", new TestEndpoint());
        OpenApiService service = new OpenApiService("API", "1.0", server.getRegisteredEndpoints());

        // Act
        Map<String, Object> spec = service.generate();

        // Assert
        @SuppressWarnings("unchecked")
        Map<String, Object> paths = (Map<String, Object>) spec.get("paths");
        @SuppressWarnings("unchecked")
        Map<String, Object> itemPath = (Map<String, Object>) paths.get("/api/items/{id}");
        @SuppressWarnings("unchecked")
        Map<String, Object> putOp = (Map<String, Object>) itemPath.get("put");
        TestSupport.assertEquals(true, putOp.get("deprecated"), "PUT /api/items/{id} should be deprecated");
    }

    // --- Test endpoint classes ---

    @ApiTag(name = "Items", description = "Item management")
    public static class TestEndpoint {
        @GET
        @Action(path = "/api/items")
        @ApiDoc(summary = "list all items", tag = "CustomTag")
        public Response listItems() {
            return new Response().OK();
        }

        @POST
        @Action(path = "/api/items")
        public Response createItem(String body) {
            return new Response().OK();
        }

        @GET
        @Action(path = "/api/items/{id}")
        public Response getItem(String id) {
            return new Response().OK();
        }

        @PUT
        @Action(path = "/api/items/{id}")
        @ApiDoc(summary = "update item", deprecated = true, description = "Full update of an item")
        public Response updateItem(String id, String body) {
            return new Response().OK();
        }
    }

    @ApiTag(name = "DataLayer")
    public static class TaggedEndpoint {
        @GET
        @Action(path = "/api/data")
        public Response getData() {
            return new Response().OK();
        }
    }

    public static class RegexVerifyEndpoint {
        @GET
        @Action(path = "/api/regex-test")
        public Response list() { return new Response().OK(); }

        @GET
        @Action(path = "/api/regex-test/{id}")
        public Response get(String id) { return new Response().OK(); }
    }

    public static class CrudEndpoint {
        @GET
        @Action(path = "/api/crud")
        public Response list() { return new Response().OK(); }

        @POST
        @Action(path = "/api/crud")
        public Response create(String body) { return new Response().OK(); }

        @PUT
        @Action(path = "/api/crud")
        public Response update(String body) { return new Response().OK(); }

        @DELETE
        @Action(path = "/api/crud")
        public Response delete() { return new Response().OK(); }
    }
}
